# Generated by Django 4.2.6 on 2024-11-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choices', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('results', models.JSONField()),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='diagnostics.diagnostic')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_results', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='questions',
            field=models.ManyToManyField(related_name='diagnostics', to='diagnostics.question'),
        ),
    ]
